### ISSUE TITLE
vscode gitlens能汉化嘛

### ISSUE THREAD

**Issue by xiongzh120** [yk47g/gitkraken-chinese#21]

**Comment by YuanXiQWQ** [comment]
https://github.com/gitkraken/vscode-gitlens/issues/577
18年开的issue, 我去看了下他们的文件, 他们还在鸽 :(

**Comment by Lingchen218** [comment]
感觉，gitkraken 不好用，要不是，Linux下这好用，我可能不会用这个，vscode里面的 gitlens ，也还行，就是commit 日志时间显示的也不给力，

**Comment by YuanXiQWQ** [comment]
他们的本地化做得一个比一个差. GitKraken 相比于 GitLens 好歹还将大部分文字作为本地化字符串(其实现在用已经本地化好的 GitKraken,你会发现还有部分功能没有本地化,因为他们压根没提取出这部分内容到 strings.json 里), 其它应用甚至连本地化文件都没有,大部分都是硬编到脚本里...... 应该是个小团体,业务不很成熟. 我曾经通过反馈邮箱咨询过他们很多问题, 如今一个回信都没有 :(

**Comment by Lingchen218** [comment]
我构建了一个汉化版本的 
https://github.com/Lingchen218/vscode-gitlens/actions/runs/10885777563
